//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWebserviceProxyDemo.CasperScanSoapClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScanResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ScanResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScannerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScanPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScanSwitchesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Md5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Sha1Field;
        
        private bool DetectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SmartWebserviceProxyDemo.CasperScanSoapClient.Detection[] DetectionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionTakenField;
        
        private bool FailedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FailureMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SmartWebserviceProxyDemo.CasperScanSoapClient.ArrayOfString ScanErrorsField;
        
        private long ScanMilliseoondsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ScannerName {
            get {
                return this.ScannerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ScannerNameField, value) != true)) {
                    this.ScannerNameField = value;
                    this.RaisePropertyChanged("ScannerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DatName {
            get {
                return this.DatNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DatNameField, value) != true)) {
                    this.DatNameField = value;
                    this.RaisePropertyChanged("DatName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ScanPath {
            get {
                return this.ScanPathField;
            }
            set {
                if ((object.ReferenceEquals(this.ScanPathField, value) != true)) {
                    this.ScanPathField = value;
                    this.RaisePropertyChanged("ScanPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ScanSwitches {
            get {
                return this.ScanSwitchesField;
            }
            set {
                if ((object.ReferenceEquals(this.ScanSwitchesField, value) != true)) {
                    this.ScanSwitchesField = value;
                    this.RaisePropertyChanged("ScanSwitches");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Md5 {
            get {
                return this.Md5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Md5Field, value) != true)) {
                    this.Md5Field = value;
                    this.RaisePropertyChanged("Md5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Sha1 {
            get {
                return this.Sha1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Sha1Field, value) != true)) {
                    this.Sha1Field = value;
                    this.RaisePropertyChanged("Sha1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool Detected {
            get {
                return this.DetectedField;
            }
            set {
                if ((this.DetectedField.Equals(value) != true)) {
                    this.DetectedField = value;
                    this.RaisePropertyChanged("Detected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public SmartWebserviceProxyDemo.CasperScanSoapClient.Detection[] Detections {
            get {
                return this.DetectionsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetectionsField, value) != true)) {
                    this.DetectionsField = value;
                    this.RaisePropertyChanged("Detections");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ActionTaken {
            get {
                return this.ActionTakenField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionTakenField, value) != true)) {
                    this.ActionTakenField = value;
                    this.RaisePropertyChanged("ActionTaken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public bool Failed {
            get {
                return this.FailedField;
            }
            set {
                if ((this.FailedField.Equals(value) != true)) {
                    this.FailedField = value;
                    this.RaisePropertyChanged("Failed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string FailureMessage {
            get {
                return this.FailureMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.FailureMessageField, value) != true)) {
                    this.FailureMessageField = value;
                    this.RaisePropertyChanged("FailureMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public SmartWebserviceProxyDemo.CasperScanSoapClient.ArrayOfString ScanErrors {
            get {
                return this.ScanErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ScanErrorsField, value) != true)) {
                    this.ScanErrorsField = value;
                    this.RaisePropertyChanged("ScanErrors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public long ScanMilliseoonds {
            get {
                return this.ScanMilliseoondsField;
            }
            set {
                if ((this.ScanMilliseoondsField.Equals(value) != true)) {
                    this.ScanMilliseoondsField = value;
                    this.RaisePropertyChanged("ScanMilliseoonds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Detection", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Detection : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VirusNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VirusTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetectTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string VirusName {
            get {
                return this.VirusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VirusNameField, value) != true)) {
                    this.VirusNameField = value;
                    this.RaisePropertyChanged("VirusName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string VirusType {
            get {
                return this.VirusTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.VirusTypeField, value) != true)) {
                    this.VirusTypeField = value;
                    this.RaisePropertyChanged("VirusType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DetectType {
            get {
                return this.DetectTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DetectTypeField, value) != true)) {
                    this.DetectTypeField = value;
                    this.RaisePropertyChanged("DetectType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CasperScanSoapClient.CasperScanSoap")]
    public interface CasperScanSoap {
        
        // CODEGEN: Generating message contract since element name ftpUri from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Scan", ReplyAction="*")]
        SmartWebserviceProxyDemo.CasperScanSoapClient.ScanResponse Scan(SmartWebserviceProxyDemo.CasperScanSoapClient.ScanRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Scan", Namespace="http://tempuri.org/", Order=0)]
        public SmartWebserviceProxyDemo.CasperScanSoapClient.ScanRequestBody Body;
        
        public ScanRequest() {
        }
        
        public ScanRequest(SmartWebserviceProxyDemo.CasperScanSoapClient.ScanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ScanRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ftpUri;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sampleName;
        
        public ScanRequestBody() {
        }
        
        public ScanRequestBody(string ftpUri, string sampleName) {
            this.ftpUri = ftpUri;
            this.sampleName = sampleName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScanResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmartWebserviceProxyDemo.CasperScanSoapClient.ScanResponseBody Body;
        
        public ScanResponse() {
        }
        
        public ScanResponse(SmartWebserviceProxyDemo.CasperScanSoapClient.ScanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ScanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SmartWebserviceProxyDemo.CasperScanSoapClient.ScanResult ScanResult;
        
        public ScanResponseBody() {
        }
        
        public ScanResponseBody(SmartWebserviceProxyDemo.CasperScanSoapClient.ScanResult ScanResult) {
            this.ScanResult = ScanResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CasperScanSoapChannel : SmartWebserviceProxyDemo.CasperScanSoapClient.CasperScanSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CasperScanSoapClient : System.ServiceModel.ClientBase<SmartWebserviceProxyDemo.CasperScanSoapClient.CasperScanSoap>, SmartWebserviceProxyDemo.CasperScanSoapClient.CasperScanSoap {
        
        public CasperScanSoapClient() {
        }
        
        public CasperScanSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CasperScanSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CasperScanSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CasperScanSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmartWebserviceProxyDemo.CasperScanSoapClient.ScanResponse SmartWebserviceProxyDemo.CasperScanSoapClient.CasperScanSoap.Scan(SmartWebserviceProxyDemo.CasperScanSoapClient.ScanRequest request) {
            return base.Channel.Scan(request);
        }
        
        public SmartWebserviceProxyDemo.CasperScanSoapClient.ScanResult Scan(string ftpUri, string sampleName) {
            SmartWebserviceProxyDemo.CasperScanSoapClient.ScanRequest inValue = new SmartWebserviceProxyDemo.CasperScanSoapClient.ScanRequest();
            inValue.Body = new SmartWebserviceProxyDemo.CasperScanSoapClient.ScanRequestBody();
            inValue.Body.ftpUri = ftpUri;
            inValue.Body.sampleName = sampleName;
            SmartWebserviceProxyDemo.CasperScanSoapClient.ScanResponse retVal = ((SmartWebserviceProxyDemo.CasperScanSoapClient.CasperScanSoap)(this)).Scan(inValue);
            return retVal.Body.ScanResult;
        }
    }
}
