//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelDCGSpsWebService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JsonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntelDCGSpsWebService.JsonResource", typeof(JsonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] HelathEvent {
            get {
                object obj = ResourceManager.GetObject("HelathEvent", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] IpmiCommandList {
            get {
                object obj = ResourceManager.GetObject("IpmiCommandList", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] IpmiWarmReset {
            get {
                object obj = ResourceManager.GetObject("IpmiWarmReset", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] McuReleaseRequestTemplate {
            get {
                object obj = ResourceManager.GetObject("McuReleaseRequestTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] MicrocodeRelease_default {
            get {
                object obj = ResourceManager.GetObject("MicrocodeRelease_default", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PurleyHealthEvent {
            get {
                object obj = ResourceManager.GetObject("PurleyHealthEvent", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;ReleaseLees&quot;:
        ///    [
        ///        {
        ///            &quot;status&quot;:&quot;Idle&quot;,
        ///            &quot;ReleaseTo&quot;:&quot;Apple_only&quot;,
        ///            &quot;Mcus&quot;:
        ///            [
        ///              {
        ///                &quot;Mcu&quot;: &quot;GenericBinaryName_0&quot;,
        ///                &quot;CPUCodeName&quot;: &quot;&quot;,
        ///                &quot;CpuSegment&quot;: &quot;Desktop&quot;,
        ///                &quot;ReleaseTarget&quot;: &quot;debug&quot;,
        ///                &quot;Stepping&quot;: &quot;&quot;,
        ///                &quot;Scope&quot;: &quot;&quot;,
        ///                &quot;CpuID&quot;: &quot;&quot;,
        ///                &quot;PlatformID&quot;: &quot;&quot;,
        ///                &quot;MicroCode&quot;: &quot;&quot;,
        ///                &quot;Pk [rest of string was truncated]&quot;;.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
