//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWebserviceProxyDemo.MetadatServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mcafeelabs.com/services/automation/sample/metadata/2.0", ConfigurationName="MetadatServiceClient.IMetaDataService")]
    public interface IMetaDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mcafeelabs.com/services/automation/sample/metadata/2.0/IMetaDataService/Ge" +
            "tMetadata", ReplyAction="http://mcafeelabs.com/services/automation/sample/metadata/2.0/IMetaDataService/Ge" +
            "tMetadataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SmartWebserviceProxyDemo.MetadatServiceClient.metadataResponse GetMetadata(string[] ftpUri, string requestId, bool unpack);
        
        // CODEGEN: Parameter 'ScanAndStoreResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://mcafeelabs.com/services/automation/sample/metadata/2.0/IMetaDataService/Sc" +
            "anAndStore", ReplyAction="http://mcafeelabs.com/services/automation/sample/metadata/2.0/IMetaDataService/Sc" +
            "anAndStoreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SmartWebserviceProxyDemo.MetadatServiceClient.ScanAndStoreResponse ScanAndStore(SmartWebserviceProxyDemo.MetadatServiceClient.ScanAndStoreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mcafeelabs.com/services/automation/sample/metadata/2.0/IMetaDataService/St" +
            "oreMetaData", ReplyAction="http://mcafeelabs.com/services/automation/sample/metadata/2.0/IMetaDataService/St" +
            "oreMetaDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void StoreMetaData(SmartWebserviceProxyDemo.MetadatServiceClient.metadata metaData);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/services/automation/sample/metadata/2.0")]
    public partial class metadataResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private metadata metadataField;
        
        private string resultMessageField;
        
        private string resultStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public metadata metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
                this.RaisePropertyChanged("metadata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string resultMessage {
            get {
                return this.resultMessageField;
            }
            set {
                this.resultMessageField = value;
                this.RaisePropertyChanged("resultMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string resultStatus {
            get {
                return this.resultStatusField;
            }
            set {
                this.resultStatusField = value;
                this.RaisePropertyChanged("resultStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public partial class metadata : object, System.ComponentModel.INotifyPropertyChanged {
        
        private sampleType[] samplesField;
        
        private perfmetricType perfmetricField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("sample", IsNullable=false)]
        public sampleType[] samples {
            get {
                return this.samplesField;
            }
            set {
                this.samplesField = value;
                this.RaisePropertyChanged("samples");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public perfmetricType perfmetric {
            get {
                return this.perfmetricField;
            }
            set {
                this.perfmetricField = value;
                this.RaisePropertyChanged("perfmetric");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public partial class sampleType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string classificationtypeField;
        
        private string classificationnameField;
        
        private string sizeField;
        
        private activityType[] activitiesField;
        
        private string[] flagsField;
        
        private virtranHitTypeName[] virtranhittypesField;
        
        private featureType[] featuresField;
        
        private fingerprintType[] fingerprintsField;
        
        private hashType[] hashesField;
        
        private systemClassificationType[] systemclassificationsField;
        
        private peGeometryType pegeometryField;
        
        private behaviorActionCollection[] behaviorsField;
        
        private sampleSourceType[] sourcesField;
        
        private uriType[] urisField;
        
        private ruleType[] rulesField;
        
        private detectionType[] detectionsField;
        
        private sampleRelationshipType[] relationshipsField;
        
        private prevalenceType[] fielddataField;
        
        private packageType[] packagesField;
        
        private digitalSignatureType[] digitalsignaturesField;
        
        private System.Xml.XmlElement additionalinfoField;
        
        private datCollection datsField;
        
        private scanErrorType[] scanerrorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string classificationtype {
            get {
                return this.classificationtypeField;
            }
            set {
                this.classificationtypeField = value;
                this.RaisePropertyChanged("classificationtype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string classificationname {
            get {
                return this.classificationnameField;
            }
            set {
                this.classificationnameField = value;
                this.RaisePropertyChanged("classificationname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("activity", IsNullable=false)]
        public activityType[] activities {
            get {
                return this.activitiesField;
            }
            set {
                this.activitiesField = value;
                this.RaisePropertyChanged("activities");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("flag", IsNullable=false)]
        public string[] flags {
            get {
                return this.flagsField;
            }
            set {
                this.flagsField = value;
                this.RaisePropertyChanged("flags");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("virtranhittype", IsNullable=false)]
        public virtranHitTypeName[] virtranhittypes {
            get {
                return this.virtranhittypesField;
            }
            set {
                this.virtranhittypesField = value;
                this.RaisePropertyChanged("virtranhittypes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("feature", IsNullable=false)]
        public featureType[] features {
            get {
                return this.featuresField;
            }
            set {
                this.featuresField = value;
                this.RaisePropertyChanged("features");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("fingerprint", IsNullable=false)]
        public fingerprintType[] fingerprints {
            get {
                return this.fingerprintsField;
            }
            set {
                this.fingerprintsField = value;
                this.RaisePropertyChanged("fingerprints");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("hash", IsNullable=false)]
        public hashType[] hashes {
            get {
                return this.hashesField;
            }
            set {
                this.hashesField = value;
                this.RaisePropertyChanged("hashes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("systemclassification", IsNullable=false)]
        public systemClassificationType[] systemclassifications {
            get {
                return this.systemclassificationsField;
            }
            set {
                this.systemclassificationsField = value;
                this.RaisePropertyChanged("systemclassifications");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public peGeometryType pegeometry {
            get {
                return this.pegeometryField;
            }
            set {
                this.pegeometryField = value;
                this.RaisePropertyChanged("pegeometry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("source", IsNullable=false)]
        public behaviorActionCollection[] behaviors {
            get {
                return this.behaviorsField;
            }
            set {
                this.behaviorsField = value;
                this.RaisePropertyChanged("behaviors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        [System.Xml.Serialization.XmlArrayItemAttribute("samplesource", IsNullable=false)]
        public sampleSourceType[] sources {
            get {
                return this.sourcesField;
            }
            set {
                this.sourcesField = value;
                this.RaisePropertyChanged("sources");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=13)]
        [System.Xml.Serialization.XmlArrayItemAttribute("uri", IsNullable=false)]
        public uriType[] uris {
            get {
                return this.urisField;
            }
            set {
                this.urisField = value;
                this.RaisePropertyChanged("uris");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=14)]
        [System.Xml.Serialization.XmlArrayItemAttribute("rule", IsNullable=false)]
        public ruleType[] rules {
            get {
                return this.rulesField;
            }
            set {
                this.rulesField = value;
                this.RaisePropertyChanged("rules");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=15)]
        [System.Xml.Serialization.XmlArrayItemAttribute("detection", IsNullable=false)]
        public detectionType[] detections {
            get {
                return this.detectionsField;
            }
            set {
                this.detectionsField = value;
                this.RaisePropertyChanged("detections");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=16)]
        [System.Xml.Serialization.XmlArrayItemAttribute("related", IsNullable=false)]
        public sampleRelationshipType[] relationships {
            get {
                return this.relationshipsField;
            }
            set {
                this.relationshipsField = value;
                this.RaisePropertyChanged("relationships");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=17)]
        [System.Xml.Serialization.XmlArrayItemAttribute("prevalence", IsNullable=false)]
        public prevalenceType[] fielddata {
            get {
                return this.fielddataField;
            }
            set {
                this.fielddataField = value;
                this.RaisePropertyChanged("fielddata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=18)]
        [System.Xml.Serialization.XmlArrayItemAttribute("package", IsNullable=false)]
        public packageType[] packages {
            get {
                return this.packagesField;
            }
            set {
                this.packagesField = value;
                this.RaisePropertyChanged("packages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=19)]
        [System.Xml.Serialization.XmlArrayItemAttribute("digitalsignature", IsNullable=false)]
        public digitalSignatureType[] digitalsignatures {
            get {
                return this.digitalsignaturesField;
            }
            set {
                this.digitalsignaturesField = value;
                this.RaisePropertyChanged("digitalsignatures");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public System.Xml.XmlElement additionalinfo {
            get {
                return this.additionalinfoField;
            }
            set {
                this.additionalinfoField = value;
                this.RaisePropertyChanged("additionalinfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public datCollection dats {
            get {
                return this.datsField;
            }
            set {
                this.datsField = value;
                this.RaisePropertyChanged("dats");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=22)]
        [System.Xml.Serialization.XmlArrayItemAttribute("scanerror", IsNullable=false)]
        public scanErrorType[] scanerrors {
            get {
                return this.scanerrorsField;
            }
            set {
                this.scanerrorsField = value;
                this.RaisePropertyChanged("scanerrors");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public partial class activityType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string typeField;
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public partial class perfmetricType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string appnameField;
        
        private string operationField;
        
        private System.DateTime startdateField;
        
        private bool startdateFieldSpecified;
        
        private System.DateTime enddateField;
        
        private bool enddateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string appname {
            get {
                return this.appnameField;
            }
            set {
                this.appnameField = value;
                this.RaisePropertyChanged("appname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("operation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime startdate {
            get {
                return this.startdateField;
            }
            set {
                this.startdateField = value;
                this.RaisePropertyChanged("startdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startdateSpecified {
            get {
                return this.startdateFieldSpecified;
            }
            set {
                this.startdateFieldSpecified = value;
                this.RaisePropertyChanged("startdateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime enddate {
            get {
                return this.enddateField;
            }
            set {
                this.enddateField = value;
                this.RaisePropertyChanged("enddate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool enddateSpecified {
            get {
                return this.enddateFieldSpecified;
            }
            set {
                this.enddateFieldSpecified = value;
                this.RaisePropertyChanged("enddateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public partial class scanErrorType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorcodeField;
        
        private string errordescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string errorcode {
            get {
                return this.errorcodeField;
            }
            set {
                this.errorcodeField = value;
                this.RaisePropertyChanged("errorcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string errordescription {
            get {
                return this.errordescriptionField;
            }
            set {
                this.errordescriptionField = value;
                this.RaisePropertyChanged("errordescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public partial class datType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public partial class datCollection : object, System.ComponentModel.INotifyPropertyChanged {
        
        private datType datField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public datType dat {
            get {
                return this.datField;
            }
            set {
                this.datField = value;
                this.RaisePropertyChanged("dat");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public partial class digitalSignatureType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string issuerField;
        
        private string subjectField;
        
        private System.DateTime signdateField;
        
        private System.DateTime expiredateField;
        
        private byte[] signkeyField;
        
        private byte[] signkeyhashField;
        
        private byte[] certhashField;
        
        private string validField;
        
        private string signtypeField;
        
        private string veralgorithmField;
        
        private string classificationtypeField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string issuer {
            get {
                return this.issuerField;
            }
            set {
                this.issuerField = value;
                this.RaisePropertyChanged("issuer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime signdate {
            get {
                return this.signdateField;
            }
            set {
                this.signdateField = value;
                this.RaisePropertyChanged("signdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime expiredate {
            get {
                return this.expiredateField;
            }
            set {
                this.expiredateField = value;
                this.RaisePropertyChanged("expiredate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="hexBinary")]
        public byte[] signkey {
            get {
                return this.signkeyField;
            }
            set {
                this.signkeyField = value;
                this.RaisePropertyChanged("signkey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="hexBinary")]
        public byte[] signkeyhash {
            get {
                return this.signkeyhashField;
            }
            set {
                this.signkeyhashField = value;
                this.RaisePropertyChanged("signkeyhash");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="hexBinary")]
        public byte[] certhash {
            get {
                return this.certhashField;
            }
            set {
                this.certhashField = value;
                this.RaisePropertyChanged("certhash");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
                this.RaisePropertyChanged("valid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string signtype {
            get {
                return this.signtypeField;
            }
            set {
                this.signtypeField = value;
                this.RaisePropertyChanged("signtype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string veralgorithm {
            get {
                return this.veralgorithmField;
            }
            set {
                this.veralgorithmField = value;
                this.RaisePropertyChanged("veralgorithm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string classificationtype {
            get {
                return this.classificationtypeField;
            }
            set {
                this.classificationtypeField = value;
                this.RaisePropertyChanged("classificationtype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="hexBinary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public partial class packageType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] platformsField;
        
        private string[] sourcesField;
        
        private string[] categoriesField;
        
        private string[] languagesField;
        
        private packageDiscoveryTypeName discoverytypeField;
        
        private bool discoverytypeFieldSpecified;
        
        private string nameField;
        
        private string manufacturerField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("platform")]
        public string[] platforms {
            get {
                return this.platformsField;
            }
            set {
                this.platformsField = value;
                this.RaisePropertyChanged("platforms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("packagesource")]
        public string[] sources {
            get {
                return this.sourcesField;
            }
            set {
                this.sourcesField = value;
                this.RaisePropertyChanged("sources");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("category")]
        public string[] categories {
            get {
                return this.categoriesField;
            }
            set {
                this.categoriesField = value;
                this.RaisePropertyChanged("categories");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("language")]
        public string[] languages {
            get {
                return this.languagesField;
            }
            set {
                this.languagesField = value;
                this.RaisePropertyChanged("languages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public packageDiscoveryTypeName discoverytype {
            get {
                return this.discoverytypeField;
            }
            set {
                this.discoverytypeField = value;
                this.RaisePropertyChanged("discoverytype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool discoverytypeSpecified {
            get {
                return this.discoverytypeFieldSpecified;
            }
            set {
                this.discoverytypeFieldSpecified = value;
                this.RaisePropertyChanged("discoverytypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
                this.RaisePropertyChanged("manufacturer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public enum packageDiscoveryTypeName {
        
        /// <remarks/>
        file,
        
        /// <remarks/>
        human,
        
        /// <remarks/>
        vendor,
        
        /// <remarks/>
        field,
        
        /// <remarks/>
        msdn,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public partial class prevalenceType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int periodinhoursField;
        
        private bool periodinhoursFieldSpecified;
        
        private string sourceField;
        
        private System.DateTime periodendingField;
        
        private bool periodendingFieldSpecified;
        
        private int countField;
        
        private bool countFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int periodinhours {
            get {
                return this.periodinhoursField;
            }
            set {
                this.periodinhoursField = value;
                this.RaisePropertyChanged("periodinhours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodinhoursSpecified {
            get {
                return this.periodinhoursFieldSpecified;
            }
            set {
                this.periodinhoursFieldSpecified = value;
                this.RaisePropertyChanged("periodinhoursSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime periodending {
            get {
                return this.periodendingField;
            }
            set {
                this.periodendingField = value;
                this.RaisePropertyChanged("periodending");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodendingSpecified {
            get {
                return this.periodendingFieldSpecified;
            }
            set {
                this.periodendingFieldSpecified = value;
                this.RaisePropertyChanged("periodendingSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
                this.RaisePropertyChanged("countSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public partial class sampleRelationshipType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] child_md5Field;
        
        private sampleRelationshipTypeName typeField;
        
        private bool typeFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="hexBinary")]
        public byte[] child_md5 {
            get {
                return this.child_md5Field;
            }
            set {
                this.child_md5Field = value;
                this.RaisePropertyChanged("child_md5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sampleRelationshipTypeName type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
                this.RaisePropertyChanged("typeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public enum sampleRelationshipTypeName {
        
        /// <remarks/>
        created,
        
        /// <remarks/>
        modified,
        
        /// <remarks/>
        renamed,
        
        /// <remarks/>
        deleted,
        
        /// <remarks/>
        unpacked,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public partial class detectionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vendorField;
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        private string datversionField;
        
        private string engineversionField;
        
        private string sourceField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string vendor {
            get {
                return this.vendorField;
            }
            set {
                this.vendorField = value;
                this.RaisePropertyChanged("vendor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
                this.RaisePropertyChanged("dateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string datversion {
            get {
                return this.datversionField;
            }
            set {
                this.datversionField = value;
                this.RaisePropertyChanged("datversion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string engineversion {
            get {
                return this.engineversionField;
            }
            set {
                this.engineversionField = value;
                this.RaisePropertyChanged("engineversion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public partial class ruleType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string nameField;
        
        private int thresholdField;
        
        private bool thresholdFieldSpecified;
        
        private int scoreField;
        
        private bool scoreFieldSpecified;
        
        private int ruleidField;
        
        private bool ruleidFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int threshold {
            get {
                return this.thresholdField;
            }
            set {
                this.thresholdField = value;
                this.RaisePropertyChanged("threshold");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool thresholdSpecified {
            get {
                return this.thresholdFieldSpecified;
            }
            set {
                this.thresholdFieldSpecified = value;
                this.RaisePropertyChanged("thresholdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
                this.RaisePropertyChanged("score");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool scoreSpecified {
            get {
                return this.scoreFieldSpecified;
            }
            set {
                this.scoreFieldSpecified = value;
                this.RaisePropertyChanged("scoreSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ruleid {
            get {
                return this.ruleidField;
            }
            set {
                this.ruleidField = value;
                this.RaisePropertyChanged("ruleid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ruleidSpecified {
            get {
                return this.ruleidFieldSpecified;
            }
            set {
                this.ruleidFieldSpecified = value;
                this.RaisePropertyChanged("ruleidSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public partial class uriType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int portField;
        
        private string protocolField;
        
        private string serverField;
        
        private uriRelationshipTypeName relationshipField;
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
                this.RaisePropertyChanged("port");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string protocol {
            get {
                return this.protocolField;
            }
            set {
                this.protocolField = value;
                this.RaisePropertyChanged("protocol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string server {
            get {
                return this.serverField;
            }
            set {
                this.serverField = value;
                this.RaisePropertyChanged("server");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uriRelationshipTypeName relationship {
            get {
                return this.relationshipField;
            }
            set {
                this.relationshipField = value;
                this.RaisePropertyChanged("relationship");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
                this.RaisePropertyChanged("dateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public enum uriRelationshipTypeName {
        
        /// <remarks/>
        source,
        
        /// <remarks/>
        contact,
        
        /// <remarks/>
        parsed,
        
        /// <remarks/>
        sms,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public partial class sampleSourceType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
                this.RaisePropertyChanged("dateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public partial class behaviorType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string actornameField;
        
        private behaviorObjectType actortypeField;
        
        private bool actortypeFieldSpecified;
        
        private string actor_md5Field;
        
        private string actionField;
        
        private string targetnameField;
        
        private behaviorObjectType targettypeField;
        
        private bool targettypeFieldSpecified;
        
        private string target_md5Field;
        
        private behaviorDataType behaviordatatypeField;
        
        private bool behaviordatatypeFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string actorname {
            get {
                return this.actornameField;
            }
            set {
                this.actornameField = value;
                this.RaisePropertyChanged("actorname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public behaviorObjectType actortype {
            get {
                return this.actortypeField;
            }
            set {
                this.actortypeField = value;
                this.RaisePropertyChanged("actortype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actortypeSpecified {
            get {
                return this.actortypeFieldSpecified;
            }
            set {
                this.actortypeFieldSpecified = value;
                this.RaisePropertyChanged("actortypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string actor_md5 {
            get {
                return this.actor_md5Field;
            }
            set {
                this.actor_md5Field = value;
                this.RaisePropertyChanged("actor_md5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string targetname {
            get {
                return this.targetnameField;
            }
            set {
                this.targetnameField = value;
                this.RaisePropertyChanged("targetname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public behaviorObjectType targettype {
            get {
                return this.targettypeField;
            }
            set {
                this.targettypeField = value;
                this.RaisePropertyChanged("targettype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool targettypeSpecified {
            get {
                return this.targettypeFieldSpecified;
            }
            set {
                this.targettypeFieldSpecified = value;
                this.RaisePropertyChanged("targettypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string target_md5 {
            get {
                return this.target_md5Field;
            }
            set {
                this.target_md5Field = value;
                this.RaisePropertyChanged("target_md5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public behaviorDataType behaviordatatype {
            get {
                return this.behaviordatatypeField;
            }
            set {
                this.behaviordatatypeField = value;
                this.RaisePropertyChanged("behaviordatatype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool behaviordatatypeSpecified {
            get {
                return this.behaviordatatypeFieldSpecified;
            }
            set {
                this.behaviordatatypeFieldSpecified = value;
                this.RaisePropertyChanged("behaviordatatypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public enum behaviorObjectType {
        
        /// <remarks/>
        file,
        
        /// <remarks/>
        registry,
        
        /// <remarks/>
        process,
        
        /// <remarks/>
        network,
        
        /// <remarks/>
        thread,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public enum behaviorDataType {
        
        /// <remarks/>
        @string,
        
        /// <remarks/>
        binary,
        
        /// <remarks/>
        number,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public partial class behaviorActionCollection : object, System.ComponentModel.INotifyPropertyChanged {
        
        private behaviorType[] actionField;
        
        private string nameField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("action", Order=0)]
        public behaviorType[] action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public partial class peSectionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string flagsField;
        
        private string crc32Field;
        
        private string idField;
        
        private byte[] nameField;
        
        private string vsizeField;
        
        private string rvaField;
        
        private string fsizeField;
        
        private string fofsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string flags {
            get {
                return this.flagsField;
            }
            set {
                this.flagsField = value;
                this.RaisePropertyChanged("flags");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string crc32 {
            get {
                return this.crc32Field;
            }
            set {
                this.crc32Field = value;
                this.RaisePropertyChanged("crc32");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="hexBinary")]
        public byte[] name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string vsize {
            get {
                return this.vsizeField;
            }
            set {
                this.vsizeField = value;
                this.RaisePropertyChanged("vsize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rva {
            get {
                return this.rvaField;
            }
            set {
                this.rvaField = value;
                this.RaisePropertyChanged("rva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fsize {
            get {
                return this.fsizeField;
            }
            set {
                this.fsizeField = value;
                this.RaisePropertyChanged("fsize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fofs {
            get {
                return this.fofsField;
            }
            set {
                this.fofsField = value;
                this.RaisePropertyChanged("fofs");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public partial class peGeometryType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private peSectionType[] pesectionField;
        
        private string crc32Field;
        
        private string entrypointField;
        
        private System.DateTime compiledateField;
        
        private bool compiledateFieldSpecified;
        
        private string headersizeField;
        
        private string headerflagsField;
        
        private string sectioncountField;
        
        private string codesizeField;
        
        private string initdatasizeField;
        
        private string uninitdatasizeField;
        
        private string importsizeField;
        
        private string exportsizeField;
        
        private string resourcesizeField;
        
        private string boundimportsizeField;
        
        private string appendeddatasizeField;
        
        private string headerbinField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pesection", Order=0)]
        public peSectionType[] pesection {
            get {
                return this.pesectionField;
            }
            set {
                this.pesectionField = value;
                this.RaisePropertyChanged("pesection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string crc32 {
            get {
                return this.crc32Field;
            }
            set {
                this.crc32Field = value;
                this.RaisePropertyChanged("crc32");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string entrypoint {
            get {
                return this.entrypointField;
            }
            set {
                this.entrypointField = value;
                this.RaisePropertyChanged("entrypoint");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime compiledate {
            get {
                return this.compiledateField;
            }
            set {
                this.compiledateField = value;
                this.RaisePropertyChanged("compiledate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool compiledateSpecified {
            get {
                return this.compiledateFieldSpecified;
            }
            set {
                this.compiledateFieldSpecified = value;
                this.RaisePropertyChanged("compiledateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string headersize {
            get {
                return this.headersizeField;
            }
            set {
                this.headersizeField = value;
                this.RaisePropertyChanged("headersize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string headerflags {
            get {
                return this.headerflagsField;
            }
            set {
                this.headerflagsField = value;
                this.RaisePropertyChanged("headerflags");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sectioncount {
            get {
                return this.sectioncountField;
            }
            set {
                this.sectioncountField = value;
                this.RaisePropertyChanged("sectioncount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codesize {
            get {
                return this.codesizeField;
            }
            set {
                this.codesizeField = value;
                this.RaisePropertyChanged("codesize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string initdatasize {
            get {
                return this.initdatasizeField;
            }
            set {
                this.initdatasizeField = value;
                this.RaisePropertyChanged("initdatasize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uninitdatasize {
            get {
                return this.uninitdatasizeField;
            }
            set {
                this.uninitdatasizeField = value;
                this.RaisePropertyChanged("uninitdatasize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string importsize {
            get {
                return this.importsizeField;
            }
            set {
                this.importsizeField = value;
                this.RaisePropertyChanged("importsize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string exportsize {
            get {
                return this.exportsizeField;
            }
            set {
                this.exportsizeField = value;
                this.RaisePropertyChanged("exportsize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string resourcesize {
            get {
                return this.resourcesizeField;
            }
            set {
                this.resourcesizeField = value;
                this.RaisePropertyChanged("resourcesize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string boundimportsize {
            get {
                return this.boundimportsizeField;
            }
            set {
                this.boundimportsizeField = value;
                this.RaisePropertyChanged("boundimportsize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string appendeddatasize {
            get {
                return this.appendeddatasizeField;
            }
            set {
                this.appendeddatasizeField = value;
                this.RaisePropertyChanged("appendeddatasize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string headerbin {
            get {
                return this.headerbinField;
            }
            set {
                this.headerbinField = value;
                this.RaisePropertyChanged("headerbin");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public partial class systemClassificationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        private string sourceField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
                this.RaisePropertyChanged("dateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public partial class hashType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private hashTypeName typeField;
        
        private bool typeFieldSpecified;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public hashTypeName type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
                this.RaisePropertyChanged("typeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="hexBinary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public enum hashTypeName {
        
        /// <remarks/>
        md5,
        
        /// <remarks/>
        sha1,
        
        /// <remarks/>
        sha256,
        
        /// <remarks/>
        sha512,
        
        /// <remarks/>
        crc32,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public partial class fingerprintType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string classificationtypeField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string classificationtype {
            get {
                return this.classificationtypeField;
            }
            set {
                this.classificationtypeField = value;
                this.RaisePropertyChanged("classificationtype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="hexBinary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public partial class featureType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string classField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
                this.RaisePropertyChanged("class");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mcafeelabs.com/schema/automation/sample/metadata/2.0")]
    public enum virtranHitTypeName {
        
        /// <remarks/>
        pe,
        
        /// <remarks/>
        dll,
        
        /// <remarks/>
        com,
        
        /// <remarks/>
        exe,
        
        /// <remarks/>
        htm,
        
        /// <remarks/>
        js,
        
        /// <remarks/>
        text,
        
        /// <remarks/>
        UNKNOWN,
        
        /// <remarks/>
        BOOT,
        
        /// <remarks/>
        PART,
        
        /// <remarks/>
        COM,
        
        /// <remarks/>
        SYS,
        
        /// <remarks/>
        EXE,
        
        /// <remarks/>
        NE,
        
        /// <remarks/>
        PE,
        
        /// <remarks/>
        OLE,
        
        /// <remarks/>
        WORD6,
        
        /// <remarks/>
        WORD97,
        
        /// <remarks/>
        EXCEL,
        
        /// <remarks/>
        LE,
        
        /// <remarks/>
        VBA,
        
        /// <remarks/>
        ACCESS,
        
        /// <remarks/>
        ELF,
        
        /// <remarks/>
        JS,
        
        /// <remarks/>
        VBS,
        
        /// <remarks/>
        TEXT,
        
        /// <remarks/>
        BAT,
        
        /// <remarks/>
        DLL,
        
        /// <remarks/>
        MESSAGE,
        
        /// <remarks/>
        WINMEM,
        
        /// <remarks/>
        REGISTRY,
        
        /// <remarks/>
        COOKIE,
        
        /// <remarks/>
        CLIB,
        
        /// <remarks/>
        CVERB,
        
        /// <remarks/>
        SWF,
        
        /// <remarks/>
        CEX,
        
        /// <remarks/>
        EXO,
        
        /// <remarks/>
        LAX,
        
        /// <remarks/>
        BP,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ScanAndStore", WrapperNamespace="http://mcafeelabs.com/services/automation/sample/metadata/2.0", IsWrapped=true)]
    public partial class ScanAndStoreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mcafeelabs.com/services/automation/sample/metadata/2.0", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] ftpUri;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mcafeelabs.com/services/automation/sample/metadata/2.0", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string requestId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mcafeelabs.com/services/automation/sample/metadata/2.0", Order=2)]
        public bool unpack;
        
        public ScanAndStoreRequest() {
        }
        
        public ScanAndStoreRequest(string[] ftpUri, string requestId, bool unpack) {
            this.ftpUri = ftpUri;
            this.requestId = requestId;
            this.unpack = unpack;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ScanAndStoreResponse", WrapperNamespace="http://mcafeelabs.com/services/automation/sample/metadata/2.0", IsWrapped=true)]
    public partial class ScanAndStoreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mcafeelabs.com/services/automation/sample/metadata/2.0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ScanAndStoreResult;
        
        public ScanAndStoreResponse() {
        }
        
        public ScanAndStoreResponse(string ScanAndStoreResult) {
            this.ScanAndStoreResult = ScanAndStoreResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMetaDataServiceChannel : SmartWebserviceProxyDemo.MetadatServiceClient.IMetaDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MetaDataServiceClient : System.ServiceModel.ClientBase<SmartWebserviceProxyDemo.MetadatServiceClient.IMetaDataService>, SmartWebserviceProxyDemo.MetadatServiceClient.IMetaDataService {
        
        public MetaDataServiceClient() {
        }
        
        public MetaDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MetaDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetaDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetaDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SmartWebserviceProxyDemo.MetadatServiceClient.metadataResponse GetMetadata(string[] ftpUri, string requestId, bool unpack) {
            return base.Channel.GetMetadata(ftpUri, requestId, unpack);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmartWebserviceProxyDemo.MetadatServiceClient.ScanAndStoreResponse SmartWebserviceProxyDemo.MetadatServiceClient.IMetaDataService.ScanAndStore(SmartWebserviceProxyDemo.MetadatServiceClient.ScanAndStoreRequest request) {
            return base.Channel.ScanAndStore(request);
        }
        
        public string ScanAndStore(string[] ftpUri, string requestId, bool unpack) {
            SmartWebserviceProxyDemo.MetadatServiceClient.ScanAndStoreRequest inValue = new SmartWebserviceProxyDemo.MetadatServiceClient.ScanAndStoreRequest();
            inValue.ftpUri = ftpUri;
            inValue.requestId = requestId;
            inValue.unpack = unpack;
            SmartWebserviceProxyDemo.MetadatServiceClient.ScanAndStoreResponse retVal = ((SmartWebserviceProxyDemo.MetadatServiceClient.IMetaDataService)(this)).ScanAndStore(inValue);
            return retVal.ScanAndStoreResult;
        }
        
        public void StoreMetaData(SmartWebserviceProxyDemo.MetadatServiceClient.metadata metaData) {
            base.Channel.StoreMetaData(metaData);
        }
    }
}
